### PR TITLE
ran make format

### PR DESCRIPTION
**Pull request by Sploder12**
# Description

I ran make format and fixed a comment that got squished.

Issue #

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### Testing 
ran tests

# Checklist:
	
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by emilkovacev** [comment]
Out of curiosity, what happened with the comment?

**Comment by Sploder12** [comment]
> Out of curiosity, what happened with the comment?

The comment was from `serial.c`, the comment was

```
// bit 0: something something
// bit 1: blah blah blah
// ...
```
But it became
```
// bit 0: something something bit 1: blah blah
// blah ...
```

**Comment by emilkovacev** [comment]
That may be because of an option I enabled, I may turn that off in that case

**Comment by emilkovacev** [comment]
Never mind, maybe that's part of llvm standards? Hopefully it doesn't interfere too much in the future, if it comes up again I'll take a look

**Review by emilkovacev — APPROVED** [review]
Looks good! If formatting issues come up in the future, we may want to address them down the line

**Pull request merged**
